### PR TITLE
Fix GitHub Action badge and link

### LINKED ISSUE #31: Apply Official Github Actions Status Badge
We can use the workflow status badge of workflows, which is official feature of Github Actions, like below.

image

Can't it replace broken actions status badge in readme, with this?

See also this, https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

### PR DESCRIPTION
**Pull request by item4**
fix #31

### CODE REVIEW

**Comment by item4** [comment]
@dahlia oh, it was my fault because i did not check syntax and fill URL only. i fix juxt now

**Comment by dahlia** [comment]
@item4 Thanks four your contribution! Please sign our contributor license agreement as well.

**Comment by dahlia** [comment]
@item4 Could you sign our CLA?

**Comment by item4** [comment]
@dahlia done it now

**Comment by dahlia** [comment]
@item4 Thank you! :+1:

**Pull request merged**
